name: compile-master-focal_fossa

on:
        push:
                branches: master
        pull_request:
                branches: master

jobs:
        compile:
                runs-on: ubuntu-20.04
                steps:
                - uses: actions/checkout@v2
                - name: install requirements
                  run: sudo apt install libcurl4-openssl-dev libunibreak-dev libfribidi-dev libglib2.0-dev libgtk2.0-dev
                - name: make
                  run: make
